### ISSUE TITLE
Working with MFA

### ISSUE THREAD

**Issue by dorivix** [Azure-Samples/active-directory-b2c-javascript-nodejs-webapi#26]
Hi,
I'm new with Azure AD B2C, and I try to use the web api with MFA.
I followed the all the tutorials, and I added a user that requires MFA authentication.
When I sign in with a "regular user", I'm getting a response from the api
![image](https://user-images.githubusercontent.com/68821830/95247304-5f8c3f80-081e-11eb-8c12-2c467c7c7cf6.png)

But when I sign in with MFA user (same user flow), it opens a new dialog that always has a problem.
![image](https://user-images.githubusercontent.com/68821830/95247658-cc9fd500-081e-11eb-9fdf-3015a9e2cf5a.png)

What am I doing wrong? Do I need to change something in the webapp/webapi?
Thanks

**Comment by derisen** [comment]
@dorivix the problem is likely on the client side and not related to web API.

Did you enable MFA for your user flow as in the [documentation](https://docs.microsoft.com/azure/active-directory-b2c/custom-policy-multi-factor-authentication)? Do you have an error message in the console? Also, please take a look at [this](https://docs.microsoft.com/azure/active-directory/develop/msal-handling-exceptions?tabs=javascript#errors-that-require-interaction).

**Comment by dorivix** [comment]
I managed to solve this. Thanks a lot :)
